name: ML Pipeline CI/CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: make install

      - name: Dar formato al código
        run: make format

      - name: Ejecutar entrenamiento del modelo
        id: train
        run: |
              make train | tee output.log

      - name: Publicar métricas del modelo
        if: always()
        run: |
          echo "## 🧠 Resultados del modelo" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          grep -E "Accuracy|F1 Score|Precision|Recall" output.log >> $GITHUB_STEP_SUMMARY || echo "No se encontraron métricas."


      - name: Guardar artefactos de MLflow
        uses: actions/upload-artifact@v4
        with:
          name: modelo-entrenado
          path: mlruns/
